[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
MyModule = '0x58b01d734e68f64015f2f3110aa9c88dce1bb69c3c02dd8d868a3400c13e4254'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]